[browser]
gatherUsageStats = false

[global]
developmentMode = false

[server]
headless = false
enableCORS = false
enableXsrfProtection = false
runOnSave = false

[runner]
magicEnabled = false

[theme]
base = "dark"